### ISSUE TITLE
Reddit comments do not load when video is copyright claimed.

### ISSUE THREAD

**Issue by Zebouski** [xlexi/alientube#103]
Whenever a video becomes copyright claimed (or privated, or deleted), Google+ comments don't load under this condition, which makes sense. Problem is, alientube doesn't load reddit comments either. I want to see reddit posts about that video because often in the comments of these posts, users will link to mirrors that I can watch. I have no clue if this is a big technical issue, but it would be massively helpful if you could make alientube do its thing on videos that are down. 

I am currently using Waterfox 35.0 and Alientube 1.2.3.2

**Comment by xlexi** [comment]
Can you give a link to an example video?

**Comment by Zebouski** [comment]
https://www.youtube.com/watch?v=QIMAnGiflks was the video that led me to post this.
This is what I see: http://i.imgur.com/c4JtFpO.png

**Comment by xlexi** [comment]
Thank you, will look into it
