### ISSUE TITLE
Resubmitting issue with proof -- youtu.be does not work properly.

### ISSUE THREAD

**Issue by dzamie** [xlexi/alientube#105]
This bug occurs in Firefox AlienTube version 1.2.3.2, the most recent release for Firefox I could find. If there is a more recent version which fixes this bug, I have been unable to find instructions to install the update.

I posted an issue a while back about AlienTube not properly finding comments for youtu.be (note: different from youtube.com links), but it was closed likely due to a miscommunication.

I return with proof. When using AlienTube with the Calbel video, "BARD JUKE", the only submission that shows up is /u/IAMA_dragon-AMA's submission to /r/leagueoflegends. It ignores /u/Fitzayy's submission three hours prior, most likely due to /u/Fitzayy's use of the youtu.be form of the link.

/u/IAMA_dragon-AMA's submission: http://i.imgur.com/hmYzeKN.png
/u/Fitzayy's submission, 3 hours earlier: http://i.imgur.com/l17VOKe.png

Seeing only 3 comments as opposed to the actual discussion's 443 comments is honestly rather annoying.

**Comment by xlexi** [comment]
This issue is already fixed, but I'm having trouble submitting updates to Firefox due to Mozilla having their head up theirs, I'm working on it.
