### ISSUE TITLE
Reddit comments not loading

### ISSUE THREAD

**Issue by Vatteck** [xlexi/alientube#111]
Alright, so AlienTube works pefectly in FireFox, but when I tried using it in Chrome it doesn't appear at all. Here's the console for when all extensions are disabled:

>html5player.js:115 GET chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js net::ERR_FAILED html5player.js:115 GET chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js net::ERR_FAILED html5player.js:115 GET chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js net::ERR_FAILED html5player.js:115 GET chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js net::ERR_FAILED html5player.js:115 GET chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js net::ERR_FAILED watch?v=MQiYmvrA70M&feature=youtu.be&list=PLHcsGizlfLMWpSg7i0b9wnUyEZWI-25N3:32 Resource interpreted as Image but transferred with MIME type text/x-cross-domain-policy: "https://r20---sn-ab5l6ne7.googlevideo.com/crossdomain.xml[1] ". watch?v=MQiYmvrA70M&feature=youtu.be&list=PLHcsGizlfLMWpSg7i0b9wnUyEZWI-25N3:6321 Resource interpreted as Image but transferred with MIME type text/html: "https://pubads.g.doubleclick.net/pagead/adview?ai=BBfSXM3P2VLjoMIyCMaqTgogP…NPgCgdIekAOkA5gDpAOoAwHQBJBO4AQBoAYy2AcBmBMB&sigh=6n7zZjmTbjU&sdkv=h.3.0.0[2] ". html5player.js:486 'Attr.nodeValue' is deprecated. Please use 'value' instead. Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (min-resolution: 144dpi), (-webkit-min-device-pixel-ratio: 1.5)

And here is when only AlienTube is enabled:
>html5player.js:115 GET chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js net::ERR_FAILED html5player.js:115 GET chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js net::ERR_FAILED html5player.js:115 GET chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js net::ERR_FAILED html5player.js:115 GET chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js net::ERR_FAILED html5player.js:115 GET chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js net::ERR_FAILED watch?v=MQiYmvrA70M&feature=youtu.be&list=PLHcsGizlfLMWpSg7i0b9wnUyEZWI-25N3:32 Resource interpreted as Image but transferred with MIME type text/x-cross-domain-policy: "https://r20---sn-ab5l6ne7.googlevideo.com/crossdomain.xml[3] ". watch?v=MQiYmvrA70M&feature=youtu.be&list=PLHcsGizlfLMWpSg7i0b9wnUyEZWI-25N3:6321 Resource interpreted as Image but transferred with MIME type text/html: "https://pubads.g.doubleclick.net/pagead/adview?ai=BBfSXM3P2VLjoMIyCMaqTgogP…NPgCgdIekAOkA5gDpAOoAwHQBJBO4AQBoAYy2AcBmBMB&sigh=6n7zZjmTbjU&sdkv=h.3.0.0[4] ". html5player.js:486 'Attr.nodeValue' is deprecated. Please use 'value' instead. Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (min-resolution: 144dpi), (-webkit-min-device-pixel-ratio: 1.5)

**Comment by xlexi** [comment]
Do you have any other extensions enabled when trying AlienTube? Adblockers, cookie protctors and other privacy extensions sometimes see AlienTube's connection to reddit as potentially malicious and kill it

**Comment by Vatteck** [comment]
I double checked, and everything is unchecked besides AlienTube. I tried another video and got this:

>chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js Failed to load resource: net::ERR_FAILED
https://i.ytimg.com/i/vgLMHrh-Rkui1WH8KY0b3g/1.jpg Failed to load resource: the server responded with a status of 404 (OK)
 Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (min-resolution: 144dpi), (-webkit-min-device-pixel-ratio: 1.5)
watch:1 Mixed Content: The page at 'https://www.youtube.com/watch?v=i522kd45NX8' was loaded over HTTPS, but requested an insecure image 'http://s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif'. This content should also be served over HTTPS.
s.ytimg.com/yts/jsbin/html5player-en_US-vfl6aBTRW/html5player.js:97 'KeyboardEvent.keyLocation' is deprecated. Please use 'KeyboardEvent.location' instead.


It looks like those extensions failing are actually Chrome Cast, which I never even installed.. so mildly confused about that.

**Comment by Vatteck** [comment]
Alright, I think I found the problem after some troubleshooting. Like I said, I came from the Firefox extension which showed "No Posts" and then the Google+ comments. I think in Chrome that is completely removed and just shows Google+ if there's no reddit comments? Because I found it works in some videos and some, not so much. If I'm right, I feel pretty stupid and I'm sorry for wasting your time.

**Comment by xlexi** [comment]
Ohhh, yes you change this behavior by going to to Chrome's extension page, finding AlienTube, clicking "Options" and you'll see it right there.   
Not your fault at all, I changed the default setting of this back a year ago and your Firefox install just kept its setting so you didnt notice anything.   
I'm just glad we could resolve this problem and that it's not a bug so I won't have to do any work :P
