### ISSUE TITLE
Allow us to select which posts to take comments from

### ISSUE THREAD

**Issue by LittleEndu** [xlexi/alientube#112]
Sometimes the video is linked in the body of the post and not directly as a link (or some upload bots for bigger channels do the same). You should allow us to suggest which post from which subreddit to take comments from and if a pattern is seen, try to automate it. 

Sorry for bad English and if then for the stupid idea (I think you would need dedicated server to process all that info or a P2P network which makes it hard to implement)

**Comment by xlexi** [comment]
The idea is interesting but unfortunately it's just not going to happen, I don't have the time and resources to put into something like that, and it's never been requested before, people should learn to use Reddit properly instead.

Sorry
