### ISSUE TITLE
Youtube video starting with minus (-) causes weirdness

### ISSUE THREAD

**Issue by Bulk70** [xlexi/alientube#113]
Seems to be a recurrence of this bug: #20. I would guess Reddit is treating it like an exclusion from the search. The API either returns a 503 or any result EXCEPT the correct thread. Example query: https://api.reddit.com/search.json?q=(url:3D-ZfN9puCc4Q%20OR%20url:-ZfN9puCc4Q)%20(site:youtube.com%20OR%20site:youtu.be)

**Comment by xlexi** [comment]
Ooops, thank you. Has been fixed and Chrome should update within an hour or so
