### ISSUE TITLE
Google+ Comments Not Showing if "No posts found"

### ISSUE THREAD

**Issue by Patrik333** [xlexi/alientube#115]
I would rather see Google+ comments than none at all, but if the app can't find any Reddit posts, it just displays "No posts found" without the tab to switch to the Google+ comments. Is there a way I can set it up so it loads the G+ comments for definite, and then finds Reddit comments *afterwards*?

**Comment by xlexi** [comment]
Uhm, what browser are you on?

**Comment by xlexi** [comment]
I am closing this ticket due to a lack of reply, if/when you reply I will re-open it.
