### ISSUE TITLE
Alientube does not load in Firefox

### ISSUE THREAD

**Issue by Gotolei** [xlexi/alientube#117]
Firefox 36.0.4 / Linux / v1.2.3.2
Completely stopped working over the past few days. There's been multiple firefox updates in that time frame, so not sure which one (ranging from 36.0.1 to current) is at fault, or even if it's because of Youtube.
Tested in a fresh profile to same results.

I gather AMO requirements are somehow getting in the way of updates.. is there a dev build for testing or anything?

**Comment by xlexi** [comment]
I am aware of the issues on Firefox, I am however suffering Mozilla rejecting AlienTube for irrational and arbitrary reasons and is struggling to work around their ridicolous demands. (I submitted another today and got a rejection letter 30 minutes ago) I hope to have it done this week.

You can install this if you want but it wont auto update. But if you find any bugs do share http://sc.alex.systems/847d-96efdedbaf82.xpi

**Comment by Gotolei** [comment]
Ah ok.. bummer about that. The updated version v2.1.8 works, anyways.

**Comment by dzamie** [comment]
Apparently the domain expired, and it's no longer possible to download that.

**Comment by Gotolei** [comment]
For the time being, [link.](http://www.mediafire.com/download/qua0g4fu9ubq1za/jid1-0GRQcsmyXNQRlg@jetpack.xpi)

It might be worth updating the releases page, a la ublock and youtube-center, so people can get updates without trouble even if AMO keeps refusing.

**Comment by xlexi** [comment]
AlienTube  2.0 is finally available on the Mozilla Addons thing, should resolve your issues.
