### ISSUE TITLE
Google+ comments don't load on first click

### ISSUE THREAD

**Issue by Gotolei** [xlexi/alientube#118]
Linux / Firefox 37.0 / Addon v2.1.8

Just as the title says - see screenshot.
https://gfycat.com/ClosedHarmoniousAchillestang

**Comment by xlexi** [comment]
Hello, I'm unable to reproduce your problem. Do you have any other extensions installed?

**Comment by Gotolei** [comment]
Seems to be working properly now, oddly enough. Both then and now I had/have 20+ other addons installed, so who knows what was going on :/

**Comment by xlexi** [comment]
Oh well, let me know if the issue re-appears and I will look into it
