### ISSUE TITLE
Show Google+/Youtube comments if Reddit can't be loaded

### ISSUE THREAD

**Issue by kristofferR** [xlexi/alientube#121]
If Reddit is inaccessible for some reason (work firewall, productivity block etc) it'll just keep trying to search for Reddit posts endlessly without succeeding. 

Can you either add a timeout, or at least a button on the "Searching for Reddit posts.." page to display the Google+/Youtube comments? 

That way blocking Reddit won't effectively mean also blocking Youtube comments.

**Comment by xlexi** [comment]
3d6b9143d5b07c95dc8df87f39b1c2ed5923ba87
