### ISSUE TITLE
Channel-Specific Toggling

### ISSUE THREAD

**Issue by QuintonAjStevens** [xlexi/alientube#125]
Possible enhancement; not sure if possible. 

Basically, have a feature that saves whether to use G+ comments or AlienTube for user-specified channels. 

For example, on the channel "LinusTechTips," I would like the G+ comments to be selected first because every video of theirs gets posted to Reddit, but there are never any comments; and the comments from their subscribers aren't usually immature. 

Could also just have it so if the post on Reddit doesn't have a lot of comments (configurable threshold?) or no comments on the post, then it automatically switches to G+ comments. 

Awesome extension regardless, thanks!

**Comment by xlexi** [comment]
I'm going to consider your first idea as it sounds like an interesting concept, the second suggestion is not going to happen.

**Comment by xlexi** [comment]
Hello. I decided to integrate the feature you requested, it is nearly done and should be available in the next update :) ![Preview](http://i.imgur.com/nmqlch0.png)

**Comment by QuintonAjStevens** [comment]
Wow! It looks even better implemented than I thought it'd be! Very good work! Thank you!  :D
