### ISSUE TITLE
Google+ comments don't have a "Read more" button anymore

### ISSUE THREAD

**Issue by TerraBubble** [xlexi/alientube#127]
Heeey, sry was stoned for a couple days when I wrote the original issue and when I saw your email - I thought it was about something completely unrelated xd

Anyway, the issue is still present, I've taken a screenshot showing the same comment in four different situations - I've written the exact conditions and software version below.

http://puu.sh/hA79l/5ac6f17bbd.png

(1) (top left) is when AlienTube is enabled and I've just clicked the 'g+ comments' button. No 'Read more' buttons appear for long comments, they are just truncated.

(2) (bottom left) is the same as (1) except that after clicking the 'g+ comments' button I clicked the drop down menu at the top of the g+ comments, switching from 'top comments' to 'newest first', and then back again. Now the 'Read more' buttons have appeared - so problem is somewhere in loading the g+ comments for the first time. I then tried switching between reddit and g+ comments again, and the 'Read more' buttons still show, so it's like it needs a refresh from that drop down menu before they show up.

(3) (top right) is in incognito with all extensions (except AdBlock) disabled - 'Read more' button always shows. I also clicked it so you can see the missing text.

(4) (bottom right) is in incognito with all extensions (except AlienTube) disabled (after clicking 'g+ comments' button) - 'Read more' button doesn't show. So it's definitely something with AlienTube and not an interaction with another extension.

Video I got the example from (6th one down) - I just picked a controversial one since they have the longest comments:
https://www.youtube.com/watch?v=ea6w3zp-dYY

 I'm using the newest chrome version 42.0.2311.135 (64-bit) on Mac OS X 10.8.5, and AlienTube  2.1.8 (downloaded about an hour ago).

If you could fix this then I'll donate! This plugin is what let me discover reddit :)

Thanks

**Comment by xlexi** [comment]
Hello, I have been investigating further, and it seems the reason I was unable to reproduce it was because I had already fixed it by accident in the unreleased version I'm currently testing with. So the next version should have this fixed. It will still probably be a few days before I release it because there are still some things I want to get done.

No donations are necessary. :)

**Comment by TerraBubble** [comment]
donated anyway because #420BLAZEIT
