### ISSUE TITLE
Reddit comments only load when link is opened from reddit

### ISSUE THREAD

**Issue by Rishabh2** [xlexi/alientube#130]
This seems like a really weird issue, but the Reddit comments only load when I open the video from Reddit, and not when I open it from Youtube itself. Adding "8&feature=youtube_gdata_player" does cause the extension to load, though.

**Comment by xlexi** [comment]
Can you please state your browser and extension version.

**Comment by Rishabh2** [comment]
Right. I'm on Chrome Version 42.0.2311.135 (most recent) and the extension is Version 2.3

**Comment by xlexi** [comment]
When on a youtube video page where alientube has not loaded, Can you please press ctrl+alt+J  (cmd+option+J on mac). A window or panel should appear in Chrome with lots of messages, can you please either copy the entire content in here, or take a screenshot?

**Comment by Rishabh2** [comment]
![image](https://cloud.githubusercontent.com/assets/5218040/7504187/2233d476-f3fd-11e4-8de0-937048862bcf.png)

^Here's what's on the console. 
Below is the same video opened from reddit, so the comments do load

![image](https://cloud.githubusercontent.com/assets/5218040/7504252/943234dc-f3fd-11e4-8371-708b35a65744.png)

**Comment by xlexi** [comment]
Thank you, I got what I needed, I will investigate it tomorrow

**Comment by xlexi** [comment]
I have solved the problem, AlienTube should update within the next hour
