### ISSUE TITLE
Show Alientube on this channel

### ISSUE THREAD

**Issue by XanderDesai** [xlexi/alientube#131]
Recently my youtube videos have been looking like this.
![screen shot 2015-05-07 at 1 35 07 am](https://cloud.githubusercontent.com/assets/3454582/7509027/607b723c-f459-11e4-8a8c-cbab751a1775.png)
The checkbox for showing alientube covers up the like and dislike buttons. Anyway to prevent this from showing up would be great.

**Comment by xlexi** [comment]
This seems to be caused by another extension of yours also adding its button to this panel. I will attempt to seek a solution.
