### ISSUE TITLE
Suggested videos cover description and comments in Safari for OS X

### ISSUE THREAD

**Issue by epr** [xlexi/alientube#132]
Screenshots: http://imgur.com/a/ABvYf#0

AlienTube off:
![AlienTube off](http://i.imgur.com/NsaaW7G.jpg)
AlienTube on:
![AlienTube on](http://i.imgur.com/jhC43IX.jpg)

**Comment by xlexi** [comment]
This is a known issue, support for AlienTube 1.0 is deprecated and I'm having difficulties porting the Safari version. See #93  for more information.
