### ISSUE TITLE
Add /r/coontown to exluded list

### ISSUE THREAD

**Issue by morecake3** [xlexi/alientube#134]
I could really go through my day without having to remember that /r/coontown even exists, could specific subreddits like this be blacklisted? Or at least blockable by the user

**Comment by xlexi** [comment]
Hello, you'll be happy to know I already maintain a list like this https://github.com/xlexi/alientube/blob/master/TypeScript/Preferences.ts#L173   
   
I was simply unaware of the existence of this one, I will make sure to add it by the next update.
A feature to add your own subreddits to be hidden is also in the plans (#126)

**Comment by morecake3** [comment]
Thanks!
