### ISSUE TITLE
Extension conflicts with Disconnect extension

### ISSUE THREAD

**Issue by cybrbeast** [xlexi/alientube#136]
Alientube doesn't work when Disconnect is active

https://chrome.google.com/webstore/detail/disconnect/jeoacafpbcihiomhlakheieifhpjdfeo

**Comment by xlexi** [comment]
You have installed an extension that actively blocks javascript from connecting to other sites, what exactly do you expect to happen?

You need to whitelist reddit in this extension as stated in the FAQ https://github.com/xlexi/alientube/wiki/Frequently-Asked-Questions
