### ISSUE TITLE
Support for Vimeo.com

### ISSUE THREAD

**Issue by xlexi** [xlexi/alientube#137]
AlienTube could possibly be expanded to work with Vimeo.com. 
This is a long term goal and could possibly be scrapped.

**Comment by xzoLx** [comment]
Why not all sites?  I do like how it's implemented right where the YouTube comments are, but maybe maybe for other sites there could be a one-size fits all approach?  Just spit-balling here.

**Comment by xlexi** [comment]
That is beyond the scope of what I want this extension to be, extensions that shows reddit threads for every single website is [not a new concept](https://chrome.google.com/webstore/detail/reddit-anywhere/ldocbjabkdopnncieelmeokoigpnnilb) and it's not the direction I wish to go.

**Comment by burkasaurusrex** [comment]
Oh man, Vimeo would be nice, but it would be awesome if there was someway to do this on every site (news sites, soundcloud, imdb, etc.). I love how the comments are seamlessly integrated into YouTube's site, but I'd even take a side frame or something crude that would be easier to implement across all sites.
