### ISSUE TITLE
After loading a youtube video, two instances of the video play

### ISSUE THREAD

**Issue by gtech** [xlexi/alientube#141]
When I load a new video, it will play normally, but a second identical audio stream will play about 3 seconds afterwards. The phantom audio stream does not stop if the video is paused.

**Comment by xlexi** [comment]
Hello. Can you confirm that disabling only the AlienTube extension resolves this issue?
If so, please provide your browser version and operating system

**Comment by xlexi** [comment]
Due to a lack of reply I will assume you resolved this issue yourself and will close this. Let me know if you  have this problem again.
