### ISSUE TITLE
Not working on Chromebook

### ISSUE THREAD

**Issue by anhllmn** [xlexi/alientube#143]
I recently installed alientube and get the message:
connection interrupted
Something is interrupting the connection to reddit.com and we cannot proceed, if you use software or browser extensions to filter Internet traffic like Disconnect.me you may need to whitelist Reddit.

How can I allow alientube to work in my Chromebook?  I don't see any extensions that would cause a problem.

**Comment by xlexi** [comment]
Hello, could you please try to disable your other extensions anyway, this is the best way to ensure there is not anything interfering.

**Comment by xlexi** [comment]
Due to a lack of reply for over a week I will close this issue, let me know if your issue persists.
