### ISSUE TITLE
Blank preference options and not working.

### ISSUE THREAD

**Issue by Lemminks** [xlexi/alientube#144]
I've tried installing 2.1.8.1 which I got from the website and from firefox's site, when I check addons it states that I have alientube installed, however youtube videos still show youtube comments. 
When I check the open AlienTube Preferences in the addon manager it comes up with blank options. I'm not sure if it's a failed installation cause I've been trying to install it from both websites.

Firefox 38.0.5, Have adblock and https Everywhere, have tried disabling these but it still doesn't work.

**Comment by xlexi** [comment]
Hello, with the AlienTube preferences page open, please open the developer console (keyboard shortcuts below) a panel inside Firefox should appear with some messages inside, please copy all the messages inside and paste it in here.

![Illustration of the console](http://i.imgur.com/LCDVlBC.jpg) 

__Shortcut (Windows / Linux):__ Ctrl+Shift+K
__Shortcut (Mac OSX):__ Command+Option+K

**Comment by Lemminks** [comment]
Hey man sorry for the late reply,
It's blank when I opened it, is there anything I need to type in?
![l9n02g9](https://cloud.githubusercontent.com/assets/12895088/8331713/195a4ee2-1acd-11e5-80a5-89ec9b371ffa.png)

**Comment by xlexi** [comment]
With the thing open, try to refresh the page

**Comment by Lemminks** [comment]
Sorry man still nothing

**Comment by xlexi** [comment]
That is strange, I will attempt to troubleshoot the error, but I am currently on vacation until next Thursday

**Comment by xlexi** [comment]
Hello, I have looked into your issue and found that it is already fixed in 2.2 which I submitted to Mozila's review system last April, unfortunately it has been in the review queue for 9 weeks now and is in position 81, I have no idea when Mozilla will get around to giving a sh*t.

**Comment by xlexi** [comment]
Hello, version 2.2 has been approved for Firefox and this issue should now be fixed, please update when able.
