### ISSUE TITLE
"Load more comments" links don't load comments, or load too deep

### ISSUE THREAD

**Issue by Sophira** [xlexi/alientube#147]
For some reason, the "load more comments" links are often not loading any more. It appears that AlienTube is looking for comments one layer too deep according to https://github.com/xlexi/alientube/blob/d3b01dd/TypeScript/Comment.ts#L174:

```typescript
this.commentObject.replies.data.children.forEach((commentObject) => {
```

For example, this causes comments to load one layer too deep on the /r/videos thread for https://www.youtube.com/watch?v=rmv1VhrtYRo. If you look for [KingPewPew's comment](https://www.reddit.com/r/videos/comments/if9nd/jewel_goes_undercover_to_sing_her_songs_in_a/c23azm8) on the AlienTube output, there is a "load more comments" link directly below slackie911's comment ("GERROUS GURL, DON B GERROUS"). This should load two more comment threads ([deleted], "I am pretty sure that there..." and predvestnik, "This.") but instead displays a thread replying to predvestnik's aforementioned comment (of which the reply happens to be deleted).

This behaviour is reproducible in all cases. I'm not certain if this is a Reddit change or not, but it's been happening for a while. I don't have the right build environment to test and don't know the possible consequences of making any change, so I figured I'd submit the issue first.

I hope this information is helpful!

**Comment by xlexi** [comment]
Hello, thank you for your contribution, the depth and amount of research in this bug report is wonderful and will save me a lot of time, I am investigating this issue now, and should have a solution soon
