### ISSUE TITLE
Doesn't show reddit comments unless I refresh page

### ISSUE THREAD

**Issue by NiceLasers** [xlexi/alientube#148]

**Comment by xlexi** [comment]
Hello, I'm going to need more information. What browser are you using? What exactly happens?

Does Google+ comments still show for you, or are they hidden. Do you get any error?

**Comment by NiceLasers** [comment]
Using Chrome and it shows Google+ comments with no errors (as if the extension isn't installed). Happens when I watch videos from channels, playlists, or sub boxes (go to channel, click video link on channel)

Anthony Garciahttp://www.nicelasers.com

Date: Fri, 17 Jul 2015 12:25:13 -0700

**Comment by NiceLasers** [comment]
for example https://www.youtube.com/watch?v=9qjom-EwXB4&feature=youtu.be works but when I went to his channel and clicked the video it brought me to https://www.youtube.com/watch?v=9qjom-EwXB4 which doesnt

Anthony Garciahttp://www.nicelasers.com

Date: Fri, 17 Jul 2015 12:25:13 -0700

**Comment by xlexi** [comment]
Thank you for the feedback, I will investigate this issue
