### ISSUE TITLE
YouTube crash with Greasemonkey in e10s mode

### ISSUE THREAD

**Issue by CoreDuo** [xlexi/alientube#150]
Since multi-process Firefox is inching ever closer to being released into the stable channel, it seems like a good time to file this. All of my tabs crash in e10s mode when a YouTube video is loaded with both Greasemonkey and AlienTube enabled. They work fine when either is disabled.

I'm running Firefox Developer Edition (Aurora) 41 and have also tested with a clean profile in Firefox Nightly 42 with the same results.

**Comment by xlexi** [comment]
This bug is currently being investigated and will be resolved in the next release of AlienTube. If you use Aurora as your main browser let me know and I'll get you an xpi you can install in the meantime.

**Comment by CoreDuo** [comment]
I'm currently using it as my main browser, yes. Mostly for shaking out e10s bugs before it's default in the beta channel.

**Comment by xlexi** [comment]
Hello, I have looked into this issue and is unable to replicate it. It might be possible that Firefox or Greasemonkey has been updated in the meantime to fix it, can you confirm that you still have this issue?

**Comment by CoreDuo** [comment]
It seems to be still happening to me on Firefox Aurora 42. It's only when multi-process mode is enabled. Everything works once I open the same video in a non-e10s window.

https://i.imgur.com/Hu6DJEo.png

**Comment by xlexi** [comment]
Might be a Windows specific issue, I will investigate sometime today and get back to you

**Comment by xlexi** [comment]
it appears this issue was automatically resolved by compiling against Firefox's newest SDK (JPM), so it will be resolved in the next version which was submitted for review a week ago
