### ISSUE TITLE
Sort comments by highest rated

### ISSUE THREAD

**Issue by BrennanMcDonald** [xlexi/alientube#155]
I think it would be very beneficial to have the threads sorted by highest rated so that the most relevant/popular comments would be viewed first followed by the less relevant/popular.
Example: 

*Unsored*
![Unsorted](http://i.imgur.com/DhkEHCU.png?1)

*Sorted*
![Sorted](http://i.imgur.com/DCOE3Wm.png)

**Comment by xlexi** [comment]
The current sorting is a bug that will be resolved, the sorting will improve but will probably not be exactly after the number of votes.
