### ISSUE TITLE
Doesn't load on the first try

### ISSUE THREAD

**Issue by Coregas** [xlexi/alientube#159]
The Reddit comments don't load on first page load. I ahve to open a video (I see normal comments) and then refresh the page to see reddit comments. Only extensios I use arte "unseen on facebook" and "adBlock" disable them both, nothing changed.

**Comment by xlexi** [comment]
Hello, can you please let me know what browser you are using

**Comment by Coregas** [comment]
I am using chorme 45.0.2454.85 m, The problem appears on windows 10 and on windows 7, this is the latest version of chrome. the checkbox below a video "Show AlienTube on this channel" doesnt appear too. If I open a video from my e-mail (o get emails from the channels that I am subscribet) this plugin works great but if I navigate from video to video in youtube it doesn't work, the I have to refresh the page and it is working. The url doesn't change from refreshing. So i have no idea what could be wrong.

**Comment by mig4ng** [comment]
I have the same problem, my version of chrome is Version 45.0.2454.85 m and I am using windows 8.1 currently

**Comment by Coregas** [comment]
The problem seems not to appear, has something changet in the plugint or what?  I see that Chrome has updated to Version 45.0.2454.93 m, so maybe it was a problem with it, I haven't changed any plugins.
