### ISSUE TITLE
Layout messed up in Firefox

### ISSUE THREAD

**Issue by strawlink** [xlexi/alientube#161]
Using Firefox 41.0.2 and AlienTube 2.6.0.

[Exhibit A](http://i.imgur.com/104ylgX.png) - Voting buttons are missing and there are wrong indentation in a few comments - collapsing the comments with wrong indentation causes other comments to also be wrongly indented.

[Exhibit B](http://i.imgur.com/BNHmj6a.png) - Scrolling further down, all the previous voting buttons appears, and the layout works from here on out.

**Comment by Gotolei** [comment]
Also getting this. Same browser/addon versions.

**Comment by NetNerd** [comment]
Hey there, I'm also having the issue. It seems like the issue's possibly related to text wrapping around images from the original YouTube comments (don't quote me on that, but everything's fine when I delete the YT comment container).

　

I haven't succeeded in finding the reason for it (I assume it's just a browser bug), however I do have a quick fix for it.

Setting `overflow: hidden;` on the `#alientube` or `#at_comment` elements in the inspector seems to get the layout looking right.

**Comment by OdinGitDat** [comment]
I'm having the same problems on ff 42. The solution offered by NetNerd also works for me.

**Comment by xlexi** [comment]
Hello, thank you for the report. However I must inform that support for Firefox has been discontinued and no further updates are planned, I will therefor close this issue.
