### ISSUE TITLE
Huge spacing between reddit comment and the video when I logged into reddit (in Firefox)

### ISSUE THREAD

**Issue by fireattack** [xlexi/alientube#162]
Version: 2.6.0
Firefox version: 42, can be reproduced on Nightly as well

How to reproduce:
1. Login your reddit account.
2. Open this video: https://www.youtube.com/watch?v=f9x74SlY1ik

Result: after loaded, there is huge spacing between the video and the reddit comments:

Screenshot (partial):

![shit civic owners say - youtube](https://cloud.githubusercontent.com/assets/4130991/10875174/03b277a2-80f5-11e5-892a-51c614c3ef43.png)

**Comment by xlexi** [comment]
Hello, thank you for the report. However I must report that support for Firefox has been discontinued and no further updates are planned, I will therefor close this issue.

**Comment by The0x539** [comment]
...what
