### ISSUE TITLE
Massive gap between subreddit tabs and thread.

### ISSUE THREAD

**Issue by Zachs-Kappler** [xlexi/alientube#165]
Mozilla Firefox 42.0
AlienTube 2.6.0

Lately I've noticed a 3" vertical gap in the comments layout when toggled to view subreddit posts. This disappears when viewing the Youtube comments section via the toggle button. I'm not sure if it's a change in Youtube's CSS or something from the newer versions of Firefox causing this.

**Comment by xlexi** [comment]
Hello
The Firefox version is no longer supported
