### ISSUE TITLE
Suggestion: Allow YouTube comments in one of the tabs

### ISSUE THREAD

**Issue by SsjCosty** [xlexi/alientube#167]
The default behavior of the extension is that it hides all the youtube comments and replaces them with Reddit comments, organized by tabs from what I see. It would be really cool if there were an option to have the youtube comments alongside, maybe in another "YouTube" tab, like in the following example:
![example](http://content.screencast.com/users/CostinPopescu/folders/Jing/media/3cc8fb64-b6ee-4bca-95c5-bd124cd12b04/2015-12-04_1123.png)

**Comment by xlexi** [comment]
This is already a feature, press the google plus symbol on the right side beneath the tabs

**Comment by SsjCosty** [comment]
Awesome, I didn't even think of that!
