### ISSUE TITLE
Did you plan to release alientube to the firefox's store?

### ISSUE THREAD

**Issue by aloisdg** [xlexi/alientube#180]
Hello,

AlienTube doesn't seem to be on the [firefox's addon store](https://addons.mozilla.org/en-US/firefox/search/?q=alientube&appver=46.0&platform=windows).
Do you plan to add it there?
If you want, I can see to post it myself.

Thank you for your work!

Cheers,

**Comment by fireattack** [comment]
https://github.com/xlexi/alientube/issues/163

The support for Fx version is already gone.
