### ISSUE TITLE
Official website is spam

### ISSUE THREAD

**Issue by canadianakin** [xlexi/alientube#201]
The link to the "official" website, http://alientube.co/, is compromised or intentionally hosting spam/malware.

**Comment by SuperManifolds** [comment]
The domain expired and has been acquired by godaddy, I do not own it, please forward your concerns to them

**Comment by canadianakin** [comment]
Please remove it or change it then on the extension in the Chrome store

**Comment by SuperManifolds** [comment]
I am not able to update the chrome extension Google threatens me with account ban and lawsuit, have a nice day :)
