### ISSUE TITLE
Part of youtube screen cut off on AlienTube 1.0

### ISSUE THREAD

**Issue by Camsy** [xlexi/alientube#76]
So I just downloaded the extension and it seems really awesome, only problem is that it hides a bunch of important stuff on the side of the video screen, including the fullsize icon and number of views. I've attached photos showing what it looks like with and without the add on. I'd love to use this extension but I can't when it messes up youtubes UI so much. 
![screen shot 2014-10-14 at 1 23 15 am](https://cloud.githubusercontent.com/assets/8799567/4614871/90f4954a-52e4-11e4-84c7-9aef9e459704.png)

![screen shot 2014-10-14 at 1 21 19 am](https://cloud.githubusercontent.com/assets/8799567/4614839/3d988a28-52e4-11e4-8d41-5eae233b0aa7.png)

**Comment by solwatts** [comment]
I know this thread is a bit old, but I'm using Safari 8.0.3, and still have this issue. 
![screen shot 2015-02-18 at 11 17 31 pm](https://cloud.githubusercontent.com/assets/1747116/6261857/17ab98dc-b7c5-11e4-84e4-d5f4f8303516.png)

**Comment by RickvanPoppel** [comment]
i still have this issue; i have no idea how to access the .css file.

**Comment by felberj** [comment]
1. Become a Safari Developer

1. Edit current extension

 goto `~/Library/Safari/Extensions` and unpack the extension by following this guide <http://www.macosxtips.co.uk/index_files/extract-code-from-safari-extensions.php>

 Then go to `PATH/TO/THE/EXTRACTED/FOLDER/res` and remove following lines in the screen.css
 ```
 #watch7-sidebar {
    margin-left: 655px !important;
 }
 ```

1. Add the Extension

 In the toolbar (?) of safari, click on 'Develop' (if its not visible, you have to display it in the settings of safari) and then click on 'show extension builder'.

 Then click on the plus on the bottom left and add your folder. Then click on the 'install' button on the top right corner and there you go

DISCLAIMER: I'm not sure if this 'guide' is correct, as I did it from my head. If there are any errors, please  correct me.

@xlexi if you want, I can upload my version of your extension, so at least the safari users have this fixed until you release the next version.

**Comment by RickvanPoppel** [comment]
oh, no, excuse me, i was very unclear; i use firefox, not safari. thanks for trying to help though!

**Comment by xlexi** [comment]
AlienTube  2.0 is finally available on the Mozilla Addons thing, should resolve your issues.
Safari is not done yet.

**Comment by xlexi** [comment]
I am closing this as a duplicate, please pay attention to the following thread for now: https://github.com/xlexi/alientube/issues/93   
I am nearly done, I'm just having some problems with the new preferences page.
