### ISSUE TITLE
TypeError: Cannot read property 'subreddit' of undefined

### ISSUE THREAD

**Issue by sobran** [xlexi/alientube#94]
Whenever alientube doesn't find a post with a score above the one i specified in the settings (100) i get this error message.

http://i.imgur.com/AcUflXz.png

These are my settings:
http://i.imgur.com/ZePraVn.png

Example video with error: https://www.youtube.com/watch?v=deL_gi99Vn4
Example video without: https://www.youtube.com/watch?v=nnnj_wgo0dU

**Comment by xlexi** [comment]
Thank you mate, a detailed bug report like this warms my heart. I will investigate it as soon as I have the time

**Comment by sobran** [comment]
Thank you very much. Can't wait for the update.

**Comment by xlexi** [comment]
it should have already updated, if not you can try to force it by either reinstalling it, or clicking "Developer Mode" and then "Update Extensions Now"

**Comment by sobran** [comment]
both methods didn't work still the same error. version number is still the same 2.1.3

**Comment by xlexi** [comment]
My bad, forgot to actually press publish, should show up in an hour

**Comment by sobran** [comment]
It works now. Thank you!
