### ISSUE TITLE
Infinite "load more comments" of the same comment

### ISSUE THREAD

**Issue by tYGjQCsvVI** [xlexi/alientube#98]
https://www.youtube.com/watch?v=8Af372EQLck

The 'trees' subreddit post:-
https://i.imgur.com/BMD5VPT.png

Occurs even after a refresh, running Chromium x64 V39.0.2171.95 on Arch Linux x64. I'm unable to test it on another machine as of now, so, I have to assume it's a global issue. If not, the extension isn't logging anything to the page's console nor is it logging anything to it's background page's console, so I have no idea how to acquire logs.

**Comment by xlexi** [comment]
I was able to reproduce your issue, I will look into it.
Thank you

**Comment by tYGjQCsvVI** [comment]
Found another example of it:-

https://www.youtube.com/watch?v=ZyhrYis509A

BDSM subreddit, /u/Chlorostorm's post.

**Comment by xlexi** [comment]
This was an issue on Reddit's side which is now fixed
