### ISSUE TITLE
Some Youtube videos not loading reddit discussion threads

### ISSUE THREAD

**Issue by Caspy7** [xlexi/alientube#99]
According to Firefox I have the most recent available build: 1.2.3.2

When I went to this thread 
http://www.reddit.com/r/rust/comments/2smgzr/servo_building_a_parallel_browser/
and opened the youtube link no reddit discussion posts were found.
I have since submitted the youtube link to /r/firefox and see that now firefox gets its own discussion tab, but /r/rust is still absent.

**Comment by xlexi** [comment]
It works in the latest version for Chrome, see #77 

 I have had some difficulties submitting AlienTube 2.0 to Mozilla because of some idiotic guidelines, still trying to find a workaround for it, but college takes up a lot of my time
